# Generated by Django 5.2.1 on 2026-05-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_koeff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(max_length=10, verbose_name='Баланс')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма кредита')),
                ('year', models.IntegerField(verbose_name='Год кредита')),
                ('percent', models.FloatField(max_length=5, verbose_name='Процентная ставка')),
                ('remains', models.FloatField(max_length=10, verbose_name='Остаток по телу кредита')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Статус кредита')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма платежа')),
                ('year', models.IntegerField(verbose_name='Год платежа')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Premia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма премии')),
                ('year', models.IntegerField(verbose_name='Год премии')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год заказа')),
                ('month', models.IntegerField(null=True, verbose_name='Месяц заказа')),
                ('payment', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('issued', models.BooleanField(default=False, verbose_name='Выдано')),
                ('description', models.TextField(blank=True, verbose_name='Описание заказа')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Статус заказа')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='ZakazItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('koeff', models.FloatField(default=1.0, max_length=10)),
                ('refund', models.BooleanField(default=False, verbose_name='Возврат')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.zakaz')),
            ],
        ),
    ]
