# Generated by Django 5.2.1 on 2026-06-16 11:01

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(max_length=10, verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма кредита')),
                ('year', models.IntegerField(verbose_name='Год кредита')),
                ('percent', models.FloatField(max_length=5, verbose_name='Процентная ставка')),
                ('remains', models.FloatField(max_length=10, verbose_name='Остаток по телу кредита')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Статус кредита')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма платежа')),
                ('year', models.IntegerField(verbose_name='Год платежа')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBalance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('money', models.FloatField(max_length=10, verbose_name='Баланс')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical balance',
                'verbose_name_plural': 'historical balances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHistoryOperation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('debit', 'Списание'), ('credit', 'Пополнение'), ('premia', 'Премия'), ('zakaz', 'Заказ'), ('refund', 'Возврат'), ('credit_payment', 'Платеж по кредиту'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Тип операции')),
                ('amount', models.FloatField(verbose_name='Сумма операции')),
                ('balance_before', models.FloatField(blank=True, null=True, verbose_name='Баланс до операции')),
                ('balance_after', models.FloatField(blank=True, null=True, verbose_name='Баланс после операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание операции')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата операции')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical history operation',
                'verbose_name_plural': 'historical history operations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('debit', 'Списание'), ('credit', 'Пополнение'), ('premia', 'Премия'), ('zakaz', 'Заказ'), ('refund', 'Возврат'), ('credit_payment', 'Платеж по кредиту'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Тип операции')),
                ('amount', models.FloatField(verbose_name='Сумма операции')),
                ('balance_before', models.FloatField(blank=True, null=True, verbose_name='Баланс до операции')),
                ('balance_after', models.FloatField(blank=True, null=True, verbose_name='Баланс после операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
            ],
        ),
        migrations.CreateModel(
            name='Premia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма премии')),
                ('year', models.IntegerField(verbose_name='Год премии')),
            ],
        ),
        migrations.CreateModel(
            name='TotalKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_km', models.FloatField(max_length=10, verbose_name='Общее количество км газопровода')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год заказа')),
                ('month', models.IntegerField(null=True, verbose_name='Месяц заказа')),
                ('payment', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('issued', models.BooleanField(default=False, verbose_name='Выдано')),
                ('description', models.TextField(blank=True, verbose_name='Номер договора')),
            ],
        ),
        migrations.CreateModel(
            name='ZakazItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('koeff', models.FloatField(default=1.0, max_length=10)),
                ('refund', models.BooleanField(default=False, verbose_name='Возврат')),
                ('profit_val', models.FloatField(default=0, max_length=10, verbose_name='Прибыль')),
                ('profit_koeff', models.FloatField(default=0, max_length=10, verbose_name='Коэффициент прибыли')),
            ],
        ),
    ]
