# Generated by Django 5.2.1 on 2026-06-16 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='main.team'),
        ),
        migrations.AddField(
            model_name='credit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.credit'),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbalance',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.team'),
        ),
        migrations.AddField(
            model_name='historicalhistoryoperation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhistoryoperation',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.team'),
        ),
        migrations.AddField(
            model_name='historyoperation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.team'),
        ),
        migrations.AddField(
            model_name='premia',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='totalkm',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_km_team', to='main.team'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория заказа'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakaz', to='main.team'),
        ),
        migrations.AddField(
            model_name='zakazitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material'),
        ),
        migrations.AddField(
            model_name='zakazitem',
            name='zakaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.zakaz'),
        ),
    ]
