# Generated by Django 5.2.1 on 2026-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakazitem',
            name='profit_koeff',
            field=models.FloatField(default=0, max_length=10, verbose_name='Коэффициент прибыли'),
        ),
        migrations.AddField(
            model_name='zakazitem',
            name='profit_val',
            field=models.FloatField(default=0, max_length=10, verbose_name='Прибыль'),
        ),
    ]
