# Generated by Django 5.2 on 2025-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='month',
            field=models.IntegerField(null=True, verbose_name='Месяц покупки'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='year',
            field=models.IntegerField(verbose_name='Год покупки'),
        ),
        migrations.AlterField(
            model_name='zapusk',
            name='year',
            field=models.IntegerField(verbose_name='Год запуска'),
        ),
    ]
