# Generated by Django 5.2.1 on 2026-05-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='credit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.credit'),
        ),
        migrations.AddField(
            model_name='premia',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='zakazitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material'),
        ),
        migrations.AddField(
            model_name='zakazitem',
            name='zakaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.zakaz'),
        ),
    ]
