# Generated by Django 5.2.1 on 2025-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='month',
            field=models.IntegerField(null=True, verbose_name='Месяц заказа'),
        ),
    ]
