# Generated by Django 5.2.1 on 2026-05-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_zakazitem_profit_koeff_zakazitem_profit_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название потребителя')),
                ('profit_val', models.FloatField(default=0, max_length=10, verbose_name='Прибыль')),
            ],
        ),
        migrations.RemoveField(
            model_name='zakazitem',
            name='profit_val',
        ),
        migrations.AddField(
            model_name='zakazitem',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.consumers', verbose_name='Потребитель'),
        ),
    ]
