# Generated by Django 5.2.1 on 2026-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Номер договора'),
        ),
    ]
