# Generated by Django 5.2.1 on 2026-02-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_zakaz_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='status',
            field=models.CharField(default='Создан', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
