# Generated by Django 5.2.1 on 2026-05-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_zakaz_description'),
        ('main', '0003_alter_ecoscore_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='main.team'),
        ),
    ]
