# Generated by Django 5.2.1 on 2026-02-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_zakaz_status'),
        ('main', '0007_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Статус заказа'),
        ),
    ]
