# Generated by Django 5.2.1 on 2026-05-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_balance_team'),
        ('main', '0004_alter_ecoscore_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakaz', to='main.team'),
        ),
    ]
