# Generated by Django 5.2.1 on 2026-03-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_zakaz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakazitem',
            name='koeff',
            field=models.FloatField(default=1.0, max_length=10),
        ),
    ]
