# Generated by Django 5.2.1 on 2026-03-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_zakazitem_koeff'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='issued',
            field=models.BooleanField(default=False, verbose_name='Выдано'),
        ),
    ]
