# Generated by Django 5.2.1 on 2026-05-27 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_zakaz_team'),
        ('main', '0005_team_auto_team_learn_grs_team_learn_ks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_km', models.FloatField(max_length=10, verbose_name='Общее количество км газопровода')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_km_team', to='main.team')),
            ],
        ),
    ]
