# Generated by Django 5.2.1 on 2026-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_zakaz_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakazitem',
            name='refund',
            field=models.BooleanField(default=False, verbose_name='Возврат'),
        ),
    ]
