# Generated by Django 5.2.1 on 2026-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_zakazitem_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание заказа'),
        ),
    ]
