# Generated by Django 5.2.1 on 2026-05-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_zakaz_category'),
        ('main', '0005_team_auto_team_learn_grs_team_learn_ks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория заказа'),
        ),
    ]
