# Generated by Django 5.2.1 on 2026-05-14 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_zakaz_description'),
        ('main', '0010_koeff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма кредита')),
                ('year', models.IntegerField(verbose_name='Год кредита')),
                ('percent', models.FloatField(max_length=5, verbose_name='Процентная ставка')),
                ('remains', models.FloatField(max_length=10, verbose_name='Остаток по телу кредита')),
                ('remains_percent', models.FloatField(max_length=5, verbose_name='Остаток по процентам')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма платежа')),
                ('year', models.IntegerField(verbose_name='Год платежа')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.credit')),
            ],
        ),
    ]
