# Generated by Django 5.2.1 on 2026-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_credit_creditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='Статус кредита'),
        ),
    ]
