# Generated by Django 5.2.1 on 2026-06-03 06:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_historicalbalance'),
        ('main', '0008_town'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHistoryOperation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('debit', 'Списание'), ('credit', 'Пополнение'), ('premia', 'Премия'), ('zakaz', 'Заказ'), ('refund', 'Возврат'), ('credit_payment', 'Платеж по кредиту'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Тип операции')),
                ('amount', models.FloatField(verbose_name='Сумма операции')),
                ('balance_before', models.FloatField(blank=True, null=True, verbose_name='Баланс до операции')),
                ('balance_after', models.FloatField(blank=True, null=True, verbose_name='Баланс после операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание операции')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата операции')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.team')),
            ],
            options={
                'verbose_name': 'historical history operation',
                'verbose_name_plural': 'historical history operations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('debit', 'Списание'), ('credit', 'Пополнение'), ('premia', 'Премия'), ('zakaz', 'Заказ'), ('refund', 'Возврат'), ('credit_payment', 'Платеж по кредиту'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Тип операции')),
                ('amount', models.FloatField(verbose_name='Сумма операции')),
                ('balance_before', models.FloatField(blank=True, null=True, verbose_name='Баланс до операции')),
                ('balance_after', models.FloatField(blank=True, null=True, verbose_name='Баланс после операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.team')),
            ],
        ),
    ]
