# Generated by Django 5.2.1 on 2026-05-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_credit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='remains',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='remains_percent',
        ),
    ]
