# Generated by Django 5.2.1 on 2026-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_remove_credit_remains_remove_credit_remains_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='remains',
            field=models.FloatField(default=200, max_length=10, verbose_name='Остаток по телу кредита'),
            preserve_default=False,
        ),
    ]
