# Generated by Django 5.2.1 on 2026-05-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_credit_remains'),
        ('main', '0010_koeff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма премии')),
                ('year', models.IntegerField(verbose_name='Год премии')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
