# Generated by Django 5.2.1 on 2026-05-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_premia'),
        ('main', '0010_koeff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapusk',
            name='month',
        ),
        migrations.AddField(
            model_name='zapusk',
            name='koeff',
            field=models.FloatField(default=1.0, max_length=10, verbose_name='Коэффициент запуска'),
        ),
        migrations.AddField(
            model_name='zapusk',
            name='profit_money',
            field=models.FloatField(default=0.0, max_length=10, verbose_name='Прибыль от запуска'),
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(limit_choices_to={'category__pk': 7}, on_delete=django.db.models.deletion.CASCADE, to='main.material', verbose_name='Название объекта')),
            ],
        ),
        migrations.AlterField(
            model_name='zapusk',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.buildings'),
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год прибыли')),
                ('amount', models.FloatField(max_length=10, verbose_name='Сумма прибыли')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.zapusk')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
