# Generated by Django 5.2.1 on 2026-05-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_remove_zapusk_month_zapusk_koeff_zapusk_profit_money_and_more'),
        ('main', '0010_koeff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapusk',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material'),
        ),
    ]
