# Generated by Django 5.2.1 on 2026-06-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год выдачи')),
                ('month', models.IntegerField(null=True, verbose_name='Месяц выдачи')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория склада')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sklad', to='main.team')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.material', verbose_name='Материал')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='mtr.sklad', verbose_name='Склад отгрузки')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='mtr.sklad', verbose_name='Склад получения')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.material', verbose_name='Материал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='mtr.sklad', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'unique_together': {('warehouse', 'material')},
            },
        ),
    ]
