# Generated by Django 5.2.1 on 2026-05-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ecoscore_team'),
        ('mtr', '0002_alter_sklad_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sklad', to='main.team'),
        ),
    ]
