# Generated by Django 5.2.1 on 2026-03-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_itemproperty_property_value'),
        ('mtr', '0003_return_sklad_skladteams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sklad',
            old_name='material',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sklad',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skladteams',
            name='sklad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mtr.sklad'),
        ),
        migrations.AlterField(
            model_name='extradition',
            name='month',
            field=models.IntegerField(null=True, verbose_name='Месяц выдачи'),
        ),
        migrations.AlterField(
            model_name='extradition',
            name='year',
            field=models.IntegerField(verbose_name='Год выдачи'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtr.sklad')),
            ],
        ),
        migrations.AlterField(
            model_name='extradition',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtr.material'),
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
