# Generated by Django 5.2.1 on 2026-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0004_rename_material_sklad_name_remove_sklad_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название склада'),
        ),
    ]
