# Generated by Django 5.2.1 on 2026-03-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0005_alter_sklad_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skladteams',
            name='material',
        ),
        migrations.RemoveField(
            model_name='skladteams',
            name='quantity',
        ),
    ]
