# Generated by Django 5.2.1 on 2026-03-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_itemproperty_property_value'),
        ('mtr', '0007_alter_material_options_alter_sklad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sklad_team', to='main.team'),
        ),
        migrations.DeleteModel(
            name='SkladTeams',
        ),
    ]
