# Generated by Django 5.2.1 on 2026-03-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0008_sklad_team_delete_skladteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='mtr.sklad', verbose_name='Склад отгрузки')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mtr.material', verbose_name='Материал')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='mtr.sklad', verbose_name='Склад получения')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
                'ordering': ['-date_time'],
            },
        ),
    ]
