# Generated by Django 5.2.1 on 2026-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtr', '0009_sklad_is_active_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория склада'),
        ),
    ]
