# Generated by Django 5.2.1 on 2026-05-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_itemproperty_property_value'),
        ('mtr', '0010_sklad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradition',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.material', verbose_name='Материал'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
