# Generated by Django 5.2.1 on 2026-05-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0009_alter_zakaz_category'),
        ('main', '0005_team_auto_team_learn_grs_team_learn_ks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма компенсации')),
                ('description', models.TextField(blank=True, verbose_name='Описание компенсации')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_compensations', to='main.material')),
            ],
        ),
        migrations.CreateModel(
            name='EcoCompensationOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_compensation', models.FloatField(verbose_name='Сумма компенсации')),
                ('description', models.TextField(blank=True, verbose_name='Описание компенсации')),
                ('zakaz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_compensations', to='bank.zakaz')),
            ],
        ),
    ]
