# Generated by Django 5.2.1 on 2026-05-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactor', '0002_alter_ecocompensation_material'),
        ('main', '0005_team_auto_team_learn_grs_team_learn_ks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocompensation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_compensations', to='main.material'),
        ),
    ]
