# Generated by Django 5.2 on 2025-04-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(default='пусто', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='Категория'),
        ),
    ]
