# Generated by Django 5.2.1 on 2026-05-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ecoscore_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoscore',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_scores', to='main.team'),
        ),
    ]
