# Generated by Django 5.2.1 on 2025-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_name_alter_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
