# Generated by Django 5.2.1 on 2025-11-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_material_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
