# Generated by Django 5.2.1 on 2026-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ecoscore_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='auto',
            field=models.IntegerField(default=0, verbose_name='Автотранспорт'),
        ),
        migrations.AddField(
            model_name='team',
            name='learn_grs',
            field=models.BooleanField(default=False, verbose_name='Оператор ГРС'),
        ),
        migrations.AddField(
            model_name='team',
            name='learn_ks',
            field=models.BooleanField(default=False, verbose_name='Инженер ГKС'),
        ),
        migrations.AddField(
            model_name='team',
            name='learn_les',
            field=models.BooleanField(default=False, verbose_name='Мастер ЛЭС'),
        ),
    ]
