# Generated by Django 5.2.1 on 2026-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_team_auto_team_learn_grs_team_learn_ks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.team', verbose_name='Команды'),
        ),
    ]
