# Generated by Django 5.2.1 on 2026-02-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
