# Generated by Django 5.2.1 on 2026-05-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='main.team', verbose_name='Команды'),
        ),
    ]
