# Generated by Django 5.2.1 on 2026-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofile_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория объекта')),
                ('eco_score', models.FloatField(default=0, max_length=10, verbose_name='Экологический балл')),
                ('profit', models.FloatField(default=0, max_length=10, verbose_name='Прибыль')),
                ('potrebiteli', models.IntegerField(default=0, verbose_name='Количество потребителей')),
            ],
        ),
    ]
