# Generated by Django 5.2.1 on 2026-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_itemproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproperty',
            name='property_value',
            field=models.CharField(max_length=200),
        ),
    ]
