# Generated by Django 5.2.1 on 2026-05-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_itemproperty_property_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koeff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koeff_value', models.FloatField(max_length=10, verbose_name='Коэффициент')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material')),
            ],
        ),
    ]
