# Generated by Django 5.2.1 on 2026-05-19 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_koeff'),
        ('mtr', '0011_alter_extradition_material_alter_stock_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль пользователя')),
                ('sklad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mtr.sklad', verbose_name='Склад')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
