# Generated by Django 5.2.1 on 2026-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='eco_score',
            field=models.FloatField(default=0, max_length=10, verbose_name='Экологический балл'),
        ),
    ]
