# Generated by Django 5.2.1 on 2026-05-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_zakazitem_profit_koeff_zakazitem_profit_val'),
        ('main', '0013_ecoscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoScoreOperation',
            fields=[
                ('ecoscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ecoscore')),
                ('operation', models.FloatField(max_length=10, verbose_name='Экологический балл')),
                ('year', models.IntegerField(verbose_name='Год операции')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_score_operations', to='bank.zakazitem', verbose_name='Позиция заказа')),
            ],
            bases=('main.ecoscore',),
        ),
    ]
