# Generated by Django 5.2.1 on 2026-05-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ecoscoreoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoscoreoperation',
            name='ecoscore_ptr',
        ),
        migrations.AddField(
            model_name='ecoscoreoperation',
            name='eco_score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.ecoscore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecoscoreoperation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ecoscore',
            name='score',
            field=models.FloatField(max_length=10, verbose_name='Всего баллов'),
        ),
    ]
